### ISSUE TITLE
Not working in patch 10.1

### ISSUE THREAD

**Issue by Crypto-Spartan** [antD97/SDPS#1]
Hi! I absolutely love this tool, I use it pretty regularly. 

I was disappointed to find out that it's not working as of patch 10.1. I tried re-launching both the game & SDPS, and I issued the command `/combatlog toggle piped` multiple times.

Would you mind taking a look and potentially fixing it?

**Comment by antD97** [comment]
Hey, sorry it took me so long to see this. Are you still having that issue? I did a quick test and it seems like things are working fine on my end. If it's still not working, go into your  `Documents/My Games/Smite/BattleGame/Logs` directory and send over your most recent combat log file.

**Comment by Crypto-Spartan** [comment]
Apologies, I saw this and then completely forgot to respond. Yes, it is working for me now. I have no idea what happened in patch 10.1, must've been a bug on Hi-Rez's side with the combatlog
